"""Code that represents a shell command."""
from __future__ import annotations

import typing as t

from aiida.orm import InstalledCode

try:
    from aiida.orm.pydantic import OrmMetadataField  # type: ignore[import-not-found]

    _HAS_NEW_MODEL_API = True
except ImportError:
    _HAS_NEW_MODEL_API = False

__all__ = ('ShellCode',)


class ShellCode(InstalledCode):
    """Code that represents a shell command.

    This code type is automatically generated by the :func:`~aiida_shell.engine.launch.launch_shell_job` function and is
    a subclass of :class:`~aiida.orm.nodes.data.code.installed.InstalledCode`. It can therefore be used for any other
    calculation job as well.
    """

    if _HAS_NEW_MODEL_API:

        class CommonField(InstalledCode.CommonField):  # type: ignore[name-defined,misc]
            """Override `default_calc_job_plugin` to default to `core.shell`."""

            default_calc_job_plugin: t.Optional[str] = OrmMetadataField(
                'core.shell',
                alias='input_plugin',
                title='Default `CalcJob` plugin',
                description=(
                    'Entry point name of the default plugin ' '(as listed in `verdi plugin list aiida.calculations`)'
                ),
                short_name='-P',
            )

        class AttributesModel(CommonField, InstalledCode.AttributesModel):  # type: ignore[name-defined,misc]
            """Attributes model with ``default_calc_job_plugin`` defaulting to ``core.shell``."""

        class ConstructorArgsModel(CommonField, InstalledCode.ConstructorArgsModel):  # type: ignore[name-defined,misc]
            """Constructor arguments model with ``default_calc_job_plugin`` defaulting to ``core.shell``."""

    else:

        class Model(InstalledCode.Model):
            """Model describing required information to create an instance."""

            default_calc_job_plugin: t.Optional[str] = 'core.shell'

    def __init__(self, *args: t.Any, default_calc_job_plugin: str = 'core.shell', **kwargs: t.Any) -> None:
        """Construct a new instance."""
        self.validate_default_calc_job_plugin(default_calc_job_plugin)
        super().__init__(*args, default_calc_job_plugin=default_calc_job_plugin, **kwargs)

    @staticmethod
    def validate_default_calc_job_plugin(default_calc_job_plugin: str) -> None:
        """Validate the default calculation job plugin.

        The ``ShellCode`` should only be used with the ``core.shell`` calculation job entry point.

        :raises ValueError: If ``default_calc_job_plugin`` is not ``core.shell``.
        """
        if default_calc_job_plugin != 'core.shell':
            raise ValueError(f'`default_calc_job_plugin` has to be `core.shell`, but got: {default_calc_job_plugin}')
